sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '6'
cache:
- node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
env:
  global:
  - secure: EniUGUT3T+ZjXmGj+nqa6PqGYJ0aqjgpm1jruanGDjgg/Cw/bkfNMd9bztl8iGVwtEpkOwXKI3RQNVR5X2vLOUUHEtyjOvwZj/BDltc/ogkTflsdnIj7YKhBVMfvKDMTBcsBjT5rsVl2aA9BE9a27qRVAUcVqlfmPSjC2VFulCXQvgwOO9RxPMN1KDXfM6Ud1N65esh9wfwjVcPpIajAlUg2AFmvAyuRUgGwQ5/JaHgHzCH+PEfRI3f3axtU0OoiHBZDpChDYfT9Rc3n8lx2bucHUIWA30rLIDkVUIPPa5zOuUWIbZbnlMJJtgoNsyDPW/ntZOmw5AnTEQLwBY05Kz+ApJzPchaz2Y+2k5at01LZ1QrnvfwnUJbxb20lnvuAiMmbIjGE5UQWGARVqm2oUZVfDVJzPqz4ASHYCLDWMXBPwKB4dGX65feQgC9SPb1JldxlEraGrXHNHwt8VYa03B0mEjgteqSAgHflREKmwGCUEfkU2CdUMdxAp5cEmXgqdxPYsaZetTOpsz+RcNIQ/qjRoF8hUwbNkIsa3kWatIWn1ubW6aTEjnHp17ioefsO0NlBPX6Bev4Z7bZ2DdVRn4LrQ9jkjdniHXaOx5tViKpPt4Qn78pPBefwFJoI1BbsC3z7TJtSC4gyMTUtbVVRGkYiFAK0i+qbVLToqGGGSpo=
  - secure: Xc2ZuQ2iQ42Ww2cXjliPW0ZvbUEKsgQVfAbaV+sZHWFy+/xd3G/td7RqNBvQuK0CaZQPB/3F0KaCogO20qjtPKsbQRvFx5a63u78RAj/J5t7iXxqwiQ7ZRPPsnt1p99KSXtxA6eMUbKq3UBbhUZAMaR03jIUpWQRIDISKghyEbF2T2a12bqSEjRKV5Xhs/8S+5M7FfyJSnYw79rzGK/Q/teFDJX5lrpn17K8XcOAPijHC0vxoCCvGfE8Bk4iTN97EV1ZQX/VA+mM0tebs9MJajxQwZJOBcFscbrBuxK/1UxWg9Z1hddYitaA+55Hp3whTWgIJD57RSumfTPYBi90JudcY63JwpEPew+s+CWf8XAHaTP6go2YklGRKIETyzmz7QfoYjzYGiSBsbka0LweHb34NpDlHZAQ52AyuQpxZorIh+tHAzy+6Fkx9SqGo+OC3mR4HBNRucbZ4whvU2+IOFIGOS6EUsVKIShNVp36dBXcUE5CtoZvxM74TJA5xfklqxT1vUq25vlyl67/V07I4xIhN3EciulxCz8NvpARG7/Yf5yaQsd6Yl2clANQb2RZUmUjpU2afT3cMwEilqQOhhk9GZ2otQBiuEYAk/MX4Hv5yUM59dTB7NEgMBOiJQ/QkwDWNWQ03dB3S5qA7rAKCFb+L9WMuI/KvfNCnrwpCDU=
